apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
    - name: env
      image: nginx
      env:
        - name: YOUR_NAME
          value: "my name is vasim"
        - name: YOUR_VILLAGE
          value: "my village is nellore"


