apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    environment: dev
    tier: frontend
  
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
