apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
spec: 
  containers:
    - name: nginx-container1
      image: nginx
      ports:  
        - containerPort: 80

    - name: side-car
      image: almalinux
      command: ["sleep, 200"]

      