apiVersion: v1
kind: pod
metadata:
  name: multi-container
  namespace: roboshop
spec: 
  conatiners:
    - name: nginx-container1
      image: nginx
      ports:  
        - containerport: 80

    - name: side-car
      image: almalinux