apiVersion: v1
kind: Pod
metadata: 
  name: web-pod1
  namespace: roboshop
  labels:
    app: web
    project: roboshop
    env: web

spec:
  containers: 
    - name: nginx-container1
      image: nginx
      ports:
        - containerPort: 80
          name: httpd-svc
      
---

apiVersion: v1
kind: Service
metadata:
  name: created-nodeport
  namespace: roboshop

spec:
  selector:
    app: web
    project: roboshop
    env: web
  ports:
    - protocol:  TCP
      port: 80
      targetPort: httpd-svc
  type: NodePort

