apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: roboshop
  labels:
    app: web
    project: roboshop
  
  spec:
    containers:
      - name: nginx-container-2
        image: nginx
        ports:
          - containerPort: 80
            name: httpd-svc
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: created-nodeport
  
  spec:
   selector:
    app: web
    project: roboshop

  ports:
    - protocol: TCP
      port: 80
      target: httpd-svc
  type: NodePort
