apiVersion: v1
kind: Pod
metadata:
  name: resource-demo

spec:
  containers:
    - name: resource
      image: nginx
      resources:
        requests:
          cpu: "100m"
          memory: "125Mi"

        limits:
          cpu: "150m"
          memory: "200Mi"


        