apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop
  labels:
    app: frontend
    env: dev
  
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: httpd-svc
---
apiVersion: v1
kind: Service
metadata:
  name: course-cluster-ip
  namespace: roboshop

spec:
  selector:
    app: frontend
    env: dev
  ports:
    - ptotocol: TCP
      port: 80
      targetPort: httpd-svc
  type: ClusterIP

