apiVersion: v1
kind: ReplicaSet
metadata: 
  name: demo-replicaset
  labels:  #every resource will have labels
    app: frontend
    project: roboshop

spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
      project: roboshop


  template:  #this one belongs to comtainer
    metadata:
      labels:
        app: frontend
        project: roboshop
    spec:
      containers:
       - name: nginx-pod
         image: nginx
         ports:
          - containerPort: 80




