apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend #name of the Deployment resoutrce
  labels: # these labels Deployment  labels, every k8 resource can have labels.
    app: nginx
spec:
  # modify replicas according to your case
  replicas: 3 #these define how many replica of containers hould it create and manage
  selector:
    matchLabels: # these labels should match with pod labels
      tier: frontend
      app: nginx
      environment: dev
      project: roboshop
  template: # this one is nothing but pod definition.
    metadata:
      labels: #these are the pod labels.
        tier: frontend
        app: nginx
        environment: dev
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx